name:                random-ladder
version:             0.1.0.0
github:              "phma/random-ladder"
license:             BSD3
author:              "Pierre Abbat"
maintainer:          "phma@bezitopo.org"
copyright:           "2022 Pierre Abbat"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/phma/random-ladder#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  random-ladder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - random-ladder
    - tasty
    - tasty-hunit
    - tasty-quickcheck
